source_code_url = 'https://github.com/iomintz/Adhesive'
# one of 'DEBUG', 'INFO', 'WARNING', 'ERROR', or 'CRITICAL'
# defaults to 'INFO'
log_level = 'INFO'

[telegram]
# access api_id and api_hash at https://my.telegram.org/apps
api_id = 1074100
api_hash = 'e51aa7c56708e0408d1709349d34e284'
# get this from The BotFather
api_token = '1526810908:AAFwqBo36BdVUjOjsC1gw4TS1mxivXOmvYk'
# this shouldn't need to be changed
session_name = 'anon'

[signal]
# signal phone number that you have registered with signald
# if this is not set, the signal bot will not run but everything else will function normally
username = '+xxxxxxxxxxx'
# update this if you're running signald as a user service or in a nonstandard location
signald_socket_path = '/var/run/signald/signald.sock'

[signal.stickers]
# get these by running `python -m adhesive.signal_auth`
# username is NOT the same as your phone number
username = '...'
password = '...'

# This is your API key for signalstickers.com
# This is optional. If present, a button to submit your converted Signal sticker pack
# to signalstickers.com will be displayed.
signalstickers_api_token = '...'
# whether to really propose sticker packs for realsies or to create PR branches but no PRs
signalstickers_api_test_mode = true
